name: Deploy to VPS

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies (use npm install instead of npm ci)
        run: |
          npm install
          npm install react-scripts --save-dev

      - name: Build React app
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npm run build

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/your-app/MainWeb
            git fetch --all
            git reset --hard origin/master
            npm install
            npm install react-scripts --save-dev
            export NODE_OPTIONS="--max-old-space-size=4096"
            npm run build
            sudo systemctl reload nginx
